main="email_worker.js"
name = "email-service-rpc"
compatibility_date = "2024-12-20"
node_compat = true

[dev]
port = 3002

[placement]
mode = "smart"

send_email = [
    {name = "SEB", destination_address = "contact@seemueller.io"},
]