name = "session-proxy-geoff-seemueller-io"
main = "./index.ts"
compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false
dev.port = 3001


[env.local]
routes = [{ pattern = "dev.geoff.seemueller.io", custom_domain = true }]
services = [
    { binding = "WORKER_SITE", service = "geoff-seemueller-io" }
]

[env.dev]
#routes = [{ pattern = "dev.geoff.seemueller.io", custom_domain = true }]
services = [
    { binding = "WORKER_SITE", service = "geoff-seemueller-io-dev" }
]

# Staging configuration
[env.staging]
#routes = [{ pattern = "geoff-staging.seemueller.io", custom_domain = true }]
services = [
    { binding = "WORKER_SITE", service = "geoff-seemueller-io-staging" }
]

# Production configuration
[env.production]
routes = [{ pattern = "geoff.seemueller.io", custom_domain = true }]
services = [
    { binding = "WORKER_SITE", service = "geoff-seemueller-io-production" }
]