name: Tests

permissions:
  pull-requests: write
  statuses: write
  checks: write
  contents: read
  actions: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, ci]
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test:all
